-- 1. Table for "Get a Quote" Leads
create table quotes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  whatsapp text,
  service_type text not null,
  budget_range text,
  deadline text,
  description text,
  status text default 'New' check (status in ('New', 'Contacted', 'In Progress', 'Won', 'Lost', 'Archived'))
);

-- 2. Table for "Work with Us" Applicants
create table applicants (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text not null,
  email text not null,
  phone text,
  city text,
  primary_skill text not null,
  years_experience text,
  portfolio_link text,
  status text default 'Applied' check (status in ('Applied', 'Screening', 'Vetted', 'Rejected'))
);

-- 3. Table for General Contact Messages
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  read boolean default false
);

-- 4. Enable Row Level Security (RLS)
-- This is important! It ensures only the frontend (with the right key) or authenticated users can access data.

alter table quotes enable row level security;
alter table applicants enable row level security;
alter table messages enable row level security;

-- Policy: Anyone can INSERT data (submit forms)
create policy "Enable insert for everyone" on quotes for insert with check (true);
create policy "Enable insert for everyone" on applicants for insert with check (true);
create policy "Enable insert for everyone" on messages for insert with check (true);

-- Policy: Allow READ access for anonymous users (TEMPORARY for initial setup)
-- NOTE: In a production app with Auth, you would restrict this to 'authenticated' users only.
create policy "Enable read for everyone" on quotes for select using (true);
create policy "Enable read for everyone" on applicants for select using (true);
create policy "Enable read for everyone" on messages for select using (true);
