-- 1. Table for "Get a Quote" Leads
create table quotes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  whatsapp text,
  service_type text not null,
  budget_range text,
  deadline text,
  description text,
  status text default 'New' check (status in ('New', 'Contacted', 'In Progress', 'Won', 'Lost', 'Archived'))
);

-- 2. Table for "Join the Team" Applicants
create table applicants (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Step 1: Identity and Role
  full_name text not null,
  email text not null,
  phone text not null,
  country text,
  city text,
  location text, -- Combined city, country
  role text not null,
  skill_level text, -- Junior, Mid, Senior
  languages text,

  -- Step 2: Skills and Proof
  portfolio_link text not null,
  examples_links text,
  tools text,
  years_experience text,
  turnitin_familiar boolean default false,

  -- Step 3: Availability and Logistics
  availability_type text, -- Part-time, Full-time, Project-based
  hours_per_week text,
  timezone text,
  turnaround text,
  rate_type text, -- hourly, project
  rate_amount text,
  payment_methods text,

  -- Step 4: Fit Checks
  short_intro text,
  why_kazi text,
  linkedin_url text,

  -- Legacy fields (keeping for backwards compatibility)
  primary_skill text,

  -- Status tracking
  status text default 'new' check (status in ('new', 'screening', 'vetted', 'rejected', 'onboarded'))
);

-- 3. Table for General Contact Messages
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  read boolean default false
);

-- 4. Enable Row Level Security (RLS)
-- This is important! It ensures only the frontend (with the right key) or authenticated users can access data.

alter table quotes enable row level security;
alter table applicants enable row level security;
alter table messages enable row level security;

-- Policy: Anyone can INSERT data (submit forms)
create policy "Enable insert for everyone" on quotes for insert with check (true);
create policy "Enable insert for everyone" on applicants for insert with check (true);
create policy "Enable insert for everyone" on messages for insert with check (true);

-- Policy: Allow READ access for anonymous users (TEMPORARY for initial setup)
-- NOTE: In a production app with Auth, you would restrict this to 'authenticated' users only.
create policy "Enable read for everyone" on quotes for select using (true);
create policy "Enable read for everyone" on applicants for select using (true);
create policy "Enable read for everyone" on messages for select using (true);
